sudo: false
language: ruby
rvm:
  - 2.5.3

notifications:
  email: false

before_install:
  - 'gem update --system'

script: bundle exec rspec spec

gemfile:
  - Gemfile-rails-4.0.x
  - Gemfile-rails-4.1.x
  - Gemfile-rails-4.2.x
  - Gemfile-rails-5.0.x
  - Gemfile-rails-5.1.x
  - Gemfile-rails-5.2.x
