sudo: false
language: ruby

notifications:
  email: false

before_install:
  - 'gem update --system'

script: bundle exec rspec spec

matrix:
  include:
    - gemfile: Gemfile-rails-4.2.x
      rvm: 2.5.8
    - gemfile: Gemfile-rails-5.0.x
      rvm: 2.5.8
    - gemfile: Gemfile-rails-5.1.x
      rvm: 2.5.8
    - gemfile: Gemfile-rails-5.2.x
      rvm: 2.5.8
